# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_coment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='post',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
