# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20161101_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(default=None, upload_to=b'')),
            ],
        ),
    ]
