# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
